'use client'

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'es' | 'en' | 'fr' | 'pt' | 'de'

const translations: Record<Language, Record<string, string>> = {
    es: {
        dashboard: 'Dashboard',
        users: 'Usuarios',
        billing: 'Facturación',
        products: 'Productos',
        analytics: 'Analíticas',
        settings: 'Configuración',
        calendar: 'Calendario',
        reports: 'Reportes',
        activity: 'Actividad',
        myProfile: 'Mi Perfil',
        welcome: 'Bienvenido de vuelta',
        welcomeDesc: 'Aquí tienes un resumen de tu negocio',
        totalRevenue: 'Ingresos Totales',
        activeUsers: 'Usuarios Activos',
        conversionRate: 'Tasa de Conversión',
        responseTime: 'Tiempo de Respuesta',
        dashboardCustomizable: 'Dashboard Personalizable',
        dragWidgets: 'Arrastra los widgets para reordenarlos',
        personalizeWidgets: 'Personalizar widgets',
        monthlyRevenue: 'Ingresos Mensuales',
        activeUsersChart: 'Usuarios Activos',
        revenueChart: 'Gráfico Ingresos',
        usersChart: 'Gráfico Usuarios',
        trafficSources: 'Fuentes de tráfico',
        topProducts: 'Top productos',
        sales: 'ventas',
        jan: 'Ene', feb: 'Feb', mar: 'Mar', apr: 'Abr', may: 'May', jun: 'Jun',
        jul: 'Jul', aug: 'Ago', sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Dic',
        week: 'Sem',
        mon: 'Lun', tue: 'Mar', wed: 'Mié', thu: 'Jue', fri: 'Vie', sat: 'Sáb', sun: 'Dom',
        week1: 'Sem 1', week2: 'Sem 2', week3: 'Sem 3', week4: 'Sem 4', week5: 'Sem 5', week6: 'Sem 6',
        userManagement: 'Gestión de Usuarios',
        addUser: 'Agregar Usuario',
        editUser: 'Editar Usuario',
        exportCSV: 'Exportar CSV',
        search: 'Buscar',
        searchUsers: 'Buscar usuarios...',
        name: 'Nombre',
        email: 'Email',
        role: 'Rol',
        status: 'Estado',
        actions: 'Acciones',
        edit: 'Editar',
        delete: 'Eliminar',
        save: 'Guardar',
        cancel: 'Cancelar',
        active: 'Activo',
        inactive: 'Inactivo',
        admin: 'Admin',
        editor: 'Editor',
        userRole: 'Usuario',
        noUsers: 'No hay usuarios',
        noUsersDesc: 'Agrega el primer usuario para comenzar',
        noResults: 'No se encontraron resultados',
        showing: 'Mostrando',
        of: 'de',
        userList: 'usuarios',
        userAdded: 'Usuario agregado correctamente',
        userUpdated: 'Usuario actualizado correctamente',
        userDeleted: 'Usuario eliminado',
        usersDeleted: 'usuarios eliminados',
        confirmDelete: '¿Estás seguro de eliminar este usuario?',
        confirmDeleteMultiple: '¿Estás seguro de eliminar',
        csvExported: 'Usuarios exportados a CSV',
        orderUpdated: 'Orden actualizado',
        itemDeleted: 'Elemento eliminado',
        billingPage: 'Facturación',
        newInvoice: 'Nueva Factura',
        totalBilled: 'Total Facturado',
        paid: 'Pagado',
        pending: 'Pendiente',
        overdue: 'Vencida',
        invoices: 'Facturas',
        allStatuses: 'Todos los estados',
        paidStatus: 'Pagada',
        pendingStatus: 'Pendiente',
        overdueStatus: 'Vencida',
        client: 'Cliente',
        amount: 'Monto',
        date: 'Fecha',
        dueDate: 'Vencimiento',
        id: 'ID',
        export: 'Exportar',
        featureInDevelopment: 'Función en desarrollo',
        productsPage: 'Productos',
        addProduct: 'Agregar Producto',
        editProduct: 'Editar Producto',
        searchProducts: 'Buscar productos...',
        category: 'Categoría',
        price: 'Precio',
        stock: 'Stock',
        noProducts: 'No hay productos',
        noProductsDesc: 'Agrega el primer producto para comenzar',
        productAdded: 'Producto agregado',
        productUpdated: 'Producto actualizado',
        productDeleted: 'Producto eliminado',
        confirmDeleteProduct: '¿Eliminar este producto?',
        activeStatus: 'Activo',
        outOfStock: 'Agotado',
        events: 'Eventos',
        addEvent: 'Agregar Evento',
        eventTitle: 'Título del evento',
        eventDate: 'Fecha',
        eventDescription: 'Descripción',
        eventAdded: 'Evento agregado',
        eventDeleted: 'Evento eliminado',
        more: 'más',
        advancedReports: 'Reportes Avanzados',
        exportPDF: 'Exportar PDF',
        last7Days: 'Últimos 7 días',
        last30Days: 'Últimos 30 días',
        last3Months: 'Últimos 3 meses',
        lastYear: 'Último año',
        totalRevenuePeriod: 'Ingresos Totales',
        newUsers: 'Nuevos Usuarios',
        orders: 'Pedidos',
        avgRevenue: 'Ingreso Promedio',
        revenuePerPeriod: 'Ingresos por período',
        activeUsersPeriod: 'Usuarios activos',
        vsPreviousPeriod: 'vs período anterior',
        direct: 'Directo',
        organic: 'Orgánico',
        referred: 'Referido',
        social: 'Social',
        emailTraffic: 'Email',
        recentActivity: 'Actividad Reciente',
        clearActivity: 'Limpiar',
        allActivities: 'Todas',
        creation: 'Creación',
        update: 'Actualización',
        deletion: 'Eliminación',
        login: 'Login',
        exportAction: 'Exportación',
        noActivity: 'No hay actividad registrada',
        startedSession: 'inició sesión',
        createdUser: 'creó usuario',
        updated: 'actualizó',
        exported: 'exportó',
        deleted: 'eliminó',
        system: 'Sistema',
        personalInfo: 'Información Personal',
        changePassword: 'Cambiar Contraseña',
        currentPassword: 'Contraseña Actual',
        newPassword: 'Nueva Contraseña',
        confirmPassword: 'Confirmar Contraseña',
        updatePassword: 'Actualizar Contraseña',
        saveChanges: 'Guardar Cambios',
        clickCamera: 'Haz clic en el ícono de cámara para cambiar tu avatar',
        profileUpdated: 'Perfil actualizado correctamente',
        passwordUpdated: 'Contraseña actualizada correctamente',
        passwordsDontMatch: 'Las contraseñas no coinciden',
        passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
        signIn: 'Iniciar Sesión',
        signOut: 'Cerrar Sesión',
        password: 'Contraseña',
        demoNote: 'Demo: usa cualquier email y contraseña de 6+ caracteres',
        emailRequired: 'El email es requerido',
        passwordRequired: 'La contraseña es requerida',
        passwordMin6: 'La contraseña debe tener al menos 6 caracteres',
        loginError: 'Error al iniciar sesión',
        notifications: 'Notificaciones',
        markAllRead: 'Marcar todas como leídas',
        noNotifications: 'No hay notificaciones',
        siteName: 'Nombre del sitio',
        contactEmail: 'Email de contacto',
        language: 'Idioma',
        theme: 'Tema',
        dark: 'Oscuro',
        light: 'Claro',
        primaryColor: 'Color Primario',
        roleSystem: 'Sistema de Roles',
        roleDescription: 'Cambia tu rol para ver cómo se adaptan los permisos y el menú lateral',
        adminRole: 'Admin',
        editorRole: 'Editor',
        viewerRole: 'Viewer',
        fullAccess: 'Acceso total',
        limitedAccess: 'Gestión limitada',
        readOnly: 'Solo lectura',
        home: 'Inicio',
        task: 'Tarea',
        taskDescription: 'Descripción de la tarea',
        loading: 'Cargando...',
    },

    en: {
        dashboard: 'Dashboard',
        users: 'Users',
        billing: 'Billing',
        products: 'Products',
        analytics: 'Analytics',
        settings: 'Settings',
        calendar: 'Calendar',
        reports: 'Reports',
        activity: 'Activity',
        myProfile: 'My Profile',
        welcome: 'Welcome back',
        welcomeDesc: 'Here\'s a summary of your business',
        totalRevenue: 'Total Revenue',
        activeUsers: 'Active Users',
        conversionRate: 'Conversion Rate',
        responseTime: 'Response Time',
        dashboardCustomizable: 'Customizable Dashboard',
        dragWidgets: 'Drag widgets to reorder',
        personalizeWidgets: 'Customize widgets',
        monthlyRevenue: 'Monthly Revenue',
        activeUsersChart: 'Active Users',
        revenueChart: 'Revenue Chart',
        usersChart: 'Users Chart',
        trafficSources: 'Traffic Sources',
        topProducts: 'Top Products',
        sales: 'sales',
        jan: 'Jan', feb: 'Feb', mar: 'Mar', apr: 'Apr', may: 'May', jun: 'Jun',
        jul: 'Jul', aug: 'Aug', sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Dec',
        week: 'Week',
        mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
        week1: 'Week 1', week2: 'Week 2', week3: 'Week 3', week4: 'Week 4', week5: 'Week 5', week6: 'Week 6',
        userManagement: 'User Management',
        addUser: 'Add User',
        editUser: 'Edit User',
        exportCSV: 'Export CSV',
        search: 'Search',
        searchUsers: 'Search users...',
        name: 'Name',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        active: 'Active',
        inactive: 'Inactive',
        admin: 'Admin',
        editor: 'Editor',
        userRole: 'User',
        noUsers: 'No users',
        noUsersDesc: 'Add the first user to get started',
        noResults: 'No results found',
        showing: 'Showing',
        of: 'of',
        userList: 'users',
        userAdded: 'User added successfully',
        userUpdated: 'User updated successfully',
        userDeleted: 'User deleted',
        usersDeleted: 'users deleted',
        confirmDelete: 'Are you sure you want to delete this user?',
        confirmDeleteMultiple: 'Are you sure you want to delete',
        csvExported: 'Users exported to CSV',
        orderUpdated: 'Order updated',
        itemDeleted: 'Item deleted',
        billingPage: 'Billing',
        newInvoice: 'New Invoice',
        totalBilled: 'Total Billed',
        paid: 'Paid',
        pending: 'Pending',
        overdue: 'Overdue',
        invoices: 'Invoices',
        allStatuses: 'All statuses',
        paidStatus: 'Paid',
        pendingStatus: 'Pending',
        overdueStatus: 'Overdue',
        client: 'Client',
        amount: 'Amount',
        date: 'Date',
        dueDate: 'Due Date',
        id: 'ID',
        export: 'Export',
        featureInDevelopment: 'Feature in development',
        productsPage: 'Products',
        addProduct: 'Add Product',
        editProduct: 'Edit Product',
        searchProducts: 'Search products...',
        category: 'Category',
        price: 'Price',
        stock: 'Stock',
        noProducts: 'No products',
        noProductsDesc: 'Add the first product to get started',
        productAdded: 'Product added',
        productUpdated: 'Product updated',
        productDeleted: 'Product deleted',
        confirmDeleteProduct: 'Delete this product?',
        activeStatus: 'Active',
        outOfStock: 'Out of Stock',
        events: 'Events',
        addEvent: 'Add Event',
        eventTitle: 'Event Title',
        eventDate: 'Date',
        eventDescription: 'Description',
        eventAdded: 'Event added',
        eventDeleted: 'Event deleted',
        more: 'more',
        advancedReports: 'Advanced Reports',
        exportPDF: 'Export PDF',
        last7Days: 'Last 7 days',
        last30Days: 'Last 30 days',
        last3Months: 'Last 3 months',
        lastYear: 'Last year',
        totalRevenuePeriod: 'Total Revenue',
        newUsers: 'New Users',
        orders: 'Orders',
        avgRevenue: 'Avg Revenue',
        revenuePerPeriod: 'Revenue per period',
        activeUsersPeriod: 'Active users',
        vsPreviousPeriod: 'vs previous period',
        direct: 'Direct',
        organic: 'Organic',
        referred: 'Referred',
        social: 'Social',
        emailTraffic: 'Email',
        recentActivity: 'Recent Activity',
        clearActivity: 'Clear',
        allActivities: 'All',
        creation: 'Creation',
        update: 'Update',
        deletion: 'Deletion',
        login: 'Login',
        exportAction: 'Export',
        noActivity: 'No activity recorded',
        startedSession: 'started session',
        createdUser: 'created user',
        updated: 'updated',
        exported: 'exported',
        deleted: 'deleted',
        system: 'System',
        personalInfo: 'Personal Information',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        updatePassword: 'Update Password',
        saveChanges: 'Save Changes',
        clickCamera: 'Click the camera icon to change your avatar',
        profileUpdated: 'Profile updated successfully',
        passwordUpdated: 'Password updated successfully',
        passwordsDontMatch: 'Passwords do not match',
        passwordMinLength: 'Password must be at least 6 characters',
        signIn: 'Sign In',
        signOut: 'Sign Out',
        password: 'Password',
        demoNote: 'Demo: use any email and password (6+ chars)',
        emailRequired: 'Email is required',
        passwordRequired: 'Password is required',
        passwordMin6: 'Password must be at least 6 characters',
        loginError: 'Login error',
        notifications: 'Notifications',
        markAllRead: 'Mark all as read',
        noNotifications: 'No notifications',
        siteName: 'Site Name',
        contactEmail: 'Contact Email',
        language: 'Language',
        theme: 'Theme',
        dark: 'Dark',
        light: 'Light',
        primaryColor: 'Primary Color',
        roleSystem: 'Role System',
        roleDescription: 'Change your role to see how permissions and sidebar adapt',
        adminRole: 'Admin',
        editorRole: 'Editor',
        viewerRole: 'Viewer',
        fullAccess: 'Full access',
        limitedAccess: 'Limited management',
        readOnly: 'Read only',
        home: 'Home',
        task: 'Task',
        taskDescription: 'Task description',
        loading: 'Loading...',
    },

    fr: {
        dashboard: 'Tableau de bord',
        users: 'Utilisateurs',
        billing: 'Facturation',
        products: 'Produits',
        analytics: 'Analytique',
        settings: 'Paramètres',
        calendar: 'Calendrier',
        reports: 'Rapports',
        activity: 'Activité',
        myProfile: 'Mon Profil',
        welcome: 'Bon retour',
        welcomeDesc: 'Voici un résumé de votre entreprise',
        totalRevenue: 'Revenu Total',
        activeUsers: 'Utilisateurs Actifs',
        conversionRate: 'Taux de Conversion',
        responseTime: 'Temps de Réponse',
        dashboardCustomizable: 'Tableau de bord personnalisable',
        dragWidgets: 'Glissez les widgets pour réorganiser',
        personalizeWidgets: 'Personnaliser les widgets',
        monthlyRevenue: 'Revenu Mensuel',
        activeUsersChart: 'Utilisateurs Actifs',
        revenueChart: 'Graphique Revenus',
        usersChart: 'Graphique Utilisateurs',
        trafficSources: 'Sources de trafic',
        topProducts: 'Top produits',
        sales: 'ventes',
        jan: 'Jan', feb: 'Fév', mar: 'Mar', apr: 'Avr', may: 'Mai', jun: 'Jun',
        jul: 'Jul', aug: 'Aoû', sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Déc',
        week: 'Sem',
        mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Jeu', fri: 'Ven', sat: 'Sam', sun: 'Dim',
        week1: 'Sem 1', week2: 'Sem 2', week3: 'Sem 3', week4: 'Sem 4', week5: 'Sem 5', week6: 'Sem 6',
        userManagement: 'Gestion des Utilisateurs',
        addUser: 'Ajouter Utilisateur',
        editUser: 'Modifier Utilisateur',
        exportCSV: 'Exporter CSV',
        search: 'Rechercher',
        searchUsers: 'Rechercher des utilisateurs...',
        name: 'Nom',
        email: 'Email',
        role: 'Rôle',
        status: 'Statut',
        actions: 'Actions',
        edit: 'Modifier',
        delete: 'Supprimer',
        save: 'Enregistrer',
        cancel: 'Annuler',
        active: 'Actif',
        inactive: 'Inactif',
        admin: 'Admin',
        editor: 'Éditeur',
        userRole: 'Utilisateur',
        noUsers: 'Aucun utilisateur',
        noUsersDesc: 'Ajoutez le premier utilisateur pour commencer',
        noResults: 'Aucun résultat trouvé',
        showing: 'Affichage',
        of: 'de',
        userList: 'utilisateurs',
        userAdded: 'Utilisateur ajouté avec succès',
        userUpdated: 'Utilisateur mis à jour',
        userDeleted: 'Utilisateur supprimé',
        usersDeleted: 'utilisateurs supprimés',
        confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet utilisateur?',
        confirmDeleteMultiple: 'Êtes-vous sûr de vouloir supprimer',
        csvExported: 'Utilisateurs exportés en CSV',
        orderUpdated: 'Ordre mis à jour',
        itemDeleted: 'Élément supprimé',
        billingPage: 'Facturation',
        newInvoice: 'Nouvelle Facture',
        totalBilled: 'Total Facturé',
        paid: 'Payé',
        pending: 'En attente',
        overdue: 'En retard',
        invoices: 'Factures',
        allStatuses: 'Tous les statuts',
        paidStatus: 'Payée',
        pendingStatus: 'En attente',
        overdueStatus: 'En retard',
        client: 'Client',
        amount: 'Montant',
        date: 'Date',
        dueDate: 'Échéance',
        id: 'ID',
        export: 'Exporter',
        featureInDevelopment: 'Fonction en développement',
        productsPage: 'Produits',
        addProduct: 'Ajouter Produit',
        editProduct: 'Modifier Produit',
        searchProducts: 'Rechercher des produits...',
        category: 'Catégorie',
        price: 'Prix',
        stock: 'Stock',
        noProducts: 'Aucun produit',
        noProductsDesc: 'Ajoutez le premier produit pour commencer',
        productAdded: 'Produit ajouté',
        productUpdated: 'Produit mis à jour',
        productDeleted: 'Produit supprimé',
        confirmDeleteProduct: 'Supprimer ce produit?',
        activeStatus: 'Actif',
        outOfStock: 'Rupture de stock',
        events: 'Événements',
        addEvent: 'Ajouter un événement',
        eventTitle: 'Titre de l\'événement',
        eventDate: 'Date',
        eventDescription: 'Description',
        eventAdded: 'Événement ajouté',
        eventDeleted: 'Événement supprimé',
        more: 'plus',
        advancedReports: 'Rapports Avancés',
        exportPDF: 'Exporter PDF',
        last7Days: '7 derniers jours',
        last30Days: '30 derniers jours',
        last3Months: '3 derniers mois',
        lastYear: 'Dernière année',
        totalRevenuePeriod: 'Revenu Total',
        newUsers: 'Nouveaux Utilisateurs',
        orders: 'Commandes',
        avgRevenue: 'Revenu Moyen',
        revenuePerPeriod: 'Revenu par période',
        activeUsersPeriod: 'Utilisateurs actifs',
        vsPreviousPeriod: 'vs période précédente',
        direct: 'Direct',
        organic: 'Organique',
        referred: 'Référé',
        social: 'Social',
        emailTraffic: 'Email',
        recentActivity: 'Activité Récente',
        clearActivity: 'Effacer',
        allActivities: 'Toutes',
        creation: 'Création',
        update: 'Mise à jour',
        deletion: 'Suppression',
        login: 'Connexion',
        exportAction: 'Exportation',
        noActivity: 'Aucune activité enregistrée',
        startedSession: 'a commencé la session',
        createdUser: 'a créé l\'utilisateur',
        updated: 'a mis à jour',
        exported: 'a exporté',
        deleted: 'a supprimé',
        system: 'Système',
        personalInfo: 'Informations personnelles',
        changePassword: 'Changer le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        updatePassword: 'Mettre à jour le mot de passe',
        saveChanges: 'Enregistrer les modifications',
        clickCamera: 'Cliquez sur l\'icône de la caméra pour changer votre avatar',
        profileUpdated: 'Profil mis à jour avec succès',
        passwordUpdated: 'Mot de passe mis à jour',
        passwordsDontMatch: 'Les mots de passe ne correspondent pas',
        passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
        signIn: 'Connexion',
        signOut: 'Déconnexion',
        password: 'Mot de passe',
        demoNote: 'Démo: utilisez n\'importe quel email et mot de passe (6+ caractères)',
        emailRequired: 'L\'email est requis',
        passwordRequired: 'Le mot de passe est requis',
        passwordMin6: 'Le mot de passe doit contenir au moins 6 caractères',
        loginError: 'Erreur de connexion',
        notifications: 'Notifications',
        markAllRead: 'Tout marquer comme lu',
        noNotifications: 'Aucune notification',
        siteName: 'Nom du site',
        contactEmail: 'Email de contact',
        language: 'Langue',
        theme: 'Thème',
        dark: 'Sombre',
        light: 'Clair',
        primaryColor: 'Couleur primaire',
        roleSystem: 'Système de rôles',
        roleDescription: 'Changez votre rôle pour voir comment les permissions s\'adaptent',
        adminRole: 'Admin',
        editorRole: 'Éditeur',
        viewerRole: 'Spectateur',
        fullAccess: 'Accès total',
        limitedAccess: 'Gestion limitée',
        readOnly: 'Lecture seule',
        home: 'Accueil',
        task: 'Tâche',
        taskDescription: 'Description de la tâche',
        loading: 'Chargement...',
    },

    pt: {
        dashboard: 'Painel',
        users: 'Usuários',
        billing: 'Faturamento',
        products: 'Produtos',
        analytics: 'Análises',
        settings: 'Configurações',
        calendar: 'Calendário',
        reports: 'Relatórios',
        activity: 'Atividade',
        myProfile: 'Meu Perfil',
        welcome: 'Bem-vindo de volta',
        welcomeDesc: 'Aqui está um resumo do seu negócio',
        totalRevenue: 'Receita Total',
        activeUsers: 'Usuários Ativos',
        conversionRate: 'Taxa de Conversão',
        responseTime: 'Tempo de Resposta',
        dashboardCustomizable: 'Painel Personalizável',
        dragWidgets: 'Arraste os widgets para reordenar',
        personalizeWidgets: 'Personalizar widgets',
        monthlyRevenue: 'Receita Mensal',
        activeUsersChart: 'Usuários Ativos',
        revenueChart: 'Gráfico de Receitas',
        usersChart: 'Gráfico de Usuários',
        trafficSources: 'Fontes de tráfego',
        topProducts: 'Top produtos',
        sales: 'vendas',
        jan: 'Jan', feb: 'Fev', mar: 'Mar', apr: 'Abr', may: 'Mai', jun: 'Jun',
        jul: 'Jul', aug: 'Ago', sep: 'Set', oct: 'Out', nov: 'Nov', dec: 'Dez',
        week: 'Sem',
        mon: 'Seg', tue: 'Ter', wed: 'Qua', thu: 'Qui', fri: 'Sex', sat: 'Sáb', sun: 'Dom',
        week1: 'Sem 1', week2: 'Sem 2', week3: 'Sem 3', week4: 'Sem 4', week5: 'Sem 5', week6: 'Sem 6',
        userManagement: 'Gestão de Usuários',
        addUser: 'Adicionar Usuário',
        editUser: 'Editar Usuário',
        exportCSV: 'Exportar CSV',
        search: 'Pesquisar',
        searchUsers: 'Pesquisar usuários...',
        name: 'Nome',
        email: 'Email',
        role: 'Função',
        status: 'Status',
        actions: 'Ações',
        edit: 'Editar',
        delete: 'Excluir',
        save: 'Salvar',
        cancel: 'Cancelar',
        active: 'Ativo',
        inactive: 'Inativo',
        admin: 'Admin',
        editor: 'Editor',
        userRole: 'Usuário',
        noUsers: 'Nenhum usuário',
        noUsersDesc: 'Adicione o primeiro usuário para começar',
        noResults: 'Nenhum resultado encontrado',
        showing: 'Mostrando',
        of: 'de',
        userList: 'usuários',
        userAdded: 'Usuário adicionado com sucesso',
        userUpdated: 'Usuário atualizado',
        userDeleted: 'Usuário excluído',
        usersDeleted: 'usuários excluídos',
        confirmDelete: 'Tem certeza que deseja excluir este usuário?',
        confirmDeleteMultiple: 'Tem certeza que deseja excluir',
        csvExported: 'Usuários exportados para CSV',
        orderUpdated: 'Ordem atualizada',
        itemDeleted: 'Item excluído',
        billingPage: 'Faturamento',
        newInvoice: 'Nova Fatura',
        totalBilled: 'Total Faturado',
        paid: 'Pago',
        pending: 'Pendente',
        overdue: 'Atrasado',
        invoices: 'Faturas',
        allStatuses: 'Todos os status',
        paidStatus: 'Paga',
        pendingStatus: 'Pendente',
        overdueStatus: 'Atrasada',
        client: 'Cliente',
        amount: 'Valor',
        date: 'Data',
        dueDate: 'Vencimento',
        id: 'ID',
        export: 'Exportar',
        featureInDevelopment: 'Recurso em desenvolvimento',
        productsPage: 'Produtos',
        addProduct: 'Adicionar Produto',
        editProduct: 'Editar Produto',
        searchProducts: 'Pesquisar produtos...',
        category: 'Categoria',
        price: 'Preço',
        stock: 'Estoque',
        noProducts: 'Nenhum produto',
        noProductsDesc: 'Adicione o primeiro produto para começar',
        productAdded: 'Produto adicionado',
        productUpdated: 'Produto atualizado',
        productDeleted: 'Produto excluído',
        confirmDeleteProduct: 'Excluir este produto?',
        activeStatus: 'Ativo',
        outOfStock: 'Sem estoque',
        events: 'Eventos',
        addEvent: 'Adicionar evento',
        eventTitle: 'Título do evento',
        eventDate: 'Data',
        eventDescription: 'Descrição',
        eventAdded: 'Evento adicionado',
        eventDeleted: 'Evento excluído',
        more: 'mais',
        advancedReports: 'Relatórios Avançados',
        exportPDF: 'Exportar PDF',
        last7Days: 'Últimos 7 dias',
        last30Days: 'Últimos 30 dias',
        last3Months: 'Últimos 3 meses',
        lastYear: 'Último ano',
        totalRevenuePeriod: 'Receita Total',
        newUsers: 'Novos Usuários',
        orders: 'Pedidos',
        avgRevenue: 'Receita Média',
        revenuePerPeriod: 'Receita por período',
        activeUsersPeriod: 'Usuários ativos',
        vsPreviousPeriod: 'vs período anterior',
        direct: 'Direto',
        organic: 'Orgânico',
        referred: 'Referido',
        social: 'Social',
        emailTraffic: 'Email',
        recentActivity: 'Atividade Recente',
        clearActivity: 'Limpar',
        allActivities: 'Todas',
        creation: 'Criação',
        update: 'Atualização',
        deletion: 'Exclusão',
        login: 'Login',
        exportAction: 'Exportação',
        noActivity: 'Nenhuma atividade registrada',
        startedSession: 'iniciou sessão',
        createdUser: 'criou usuário',
        updated: 'atualizou',
        exported: 'exportou',
        deleted: 'excluiu',
        system: 'Sistema',
        personalInfo: 'Informações pessoais',
        changePassword: 'Alterar senha',
        currentPassword: 'Senha atual',
        newPassword: 'Nova senha',
        confirmPassword: 'Confirmar senha',
        updatePassword: 'Atualizar senha',
        saveChanges: 'Salvar alterações',
        clickCamera: 'Clique no ícone da câmera para alterar seu avatar',
        profileUpdated: 'Perfil atualizado com sucesso',
        passwordUpdated: 'Senha atualizada com sucesso',
        passwordsDontMatch: 'As senhas não coincidem',
        passwordMinLength: 'A senha deve ter pelo menos 6 caracteres',
        signIn: 'Entrar',
        signOut: 'Sair',
        password: 'Senha',
        demoNote: 'Demo: use qualquer email e senha (6+ caracteres)',
        emailRequired: 'O email é obrigatório',
        passwordRequired: 'A senha é obrigatória',
        passwordMin6: 'A senha deve ter pelo menos 6 caracteres',
        loginError: 'Erro no login',
        notifications: 'Notificações',
        markAllRead: 'Marcar todas como lidas',
        noNotifications: 'Nenhuma notificação',
        siteName: 'Nome do site',
        contactEmail: 'Email de contato',
        language: 'Idioma',
        theme: 'Tema',
        dark: 'Escuro',
        light: 'Claro',
        primaryColor: 'Cor primária',
        roleSystem: 'Sistema de funções',
        roleDescription: 'Altere sua função para ver como as permissões se adaptam',
        adminRole: 'Admin',
        editorRole: 'Editor',
        viewerRole: 'Visualizador',
        fullAccess: 'Acesso total',
        limitedAccess: 'Gestão limitada',
        readOnly: 'Somente leitura',
        home: 'Início',
        task: 'Tarefa',
        taskDescription: 'Descrição da tarefa',
        loading: 'Carregando...',
    },

    de: {
        dashboard: 'Dashboard',
        users: 'Benutzer',
        billing: 'Abrechnung',
        products: 'Produkte',
        analytics: 'Analytik',
        settings: 'Einstellungen',
        calendar: 'Kalender',
        reports: 'Berichte',
        activity: 'Aktivität',
        myProfile: 'Mein Profil',
        welcome: 'Willkommen zurück',
        welcomeDesc: 'Hier ist eine Zusammenfassung Ihres Unternehmens',
        totalRevenue: 'Gesamtumsatz',
        activeUsers: 'Aktive Benutzer',
        conversionRate: 'Konversionsrate',
        responseTime: 'Antwortzeit',
        dashboardCustomizable: 'Anpassbares Dashboard',
        dragWidgets: 'Widgets ziehen zum Neuordnen',
        personalizeWidgets: 'Widgets anpassen',
        monthlyRevenue: 'Monatlicher Umsatz',
        activeUsersChart: 'Aktive Benutzer',
        revenueChart: 'Umsatzdiagramm',
        usersChart: 'Benutzerdiagramm',
        trafficSources: 'Verkehrsquellen',
        topProducts: 'Top-Produkte',
        sales: 'Verkäufe',
        jan: 'Jan', feb: 'Feb', mar: 'Mär', apr: 'Apr', may: 'Mai', jun: 'Jun',
        jul: 'Jul', aug: 'Aug', sep: 'Sep', oct: 'Okt', nov: 'Nov', dec: 'Dez',
        week: 'Woche',
        mon: 'Mo', tue: 'Di', wed: 'Mi', thu: 'Do', fri: 'Fr', sat: 'Sa', sun: 'So',
        week1: 'Wo 1', week2: 'Wo 2', week3: 'Wo 3', week4: 'Wo 4', week5: 'Wo 5', week6: 'Wo 6',
        userManagement: 'Benutzerverwaltung',
        addUser: 'Benutzer hinzufügen',
        editUser: 'Benutzer bearbeiten',
        exportCSV: 'CSV exportieren',
        search: 'Suchen',
        searchUsers: 'Benutzer suchen...',
        name: 'Name',
        email: 'E-Mail',
        role: 'Rolle',
        status: 'Status',
        actions: 'Aktionen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        save: 'Speichern',
        cancel: 'Abbrechen',
        active: 'Aktiv',
        inactive: 'Inaktiv',
        admin: 'Admin',
        editor: 'Editor',
        userRole: 'Benutzer',
        noUsers: 'Keine Benutzer',
        noUsersDesc: 'Fügen Sie den ersten Benutzer hinzu',
        noResults: 'Keine Ergebnisse gefunden',
        showing: 'Anzeige',
        of: 'von',
        userList: 'Benutzer',
        userAdded: 'Benutzer erfolgreich hinzugefügt',
        userUpdated: 'Benutzer aktualisiert',
        userDeleted: 'Benutzer gelöscht',
        usersDeleted: 'Benutzer gelöscht',
        confirmDelete: 'Möchten Sie diesen Benutzer wirklich löschen?',
        confirmDeleteMultiple: 'Möchten Sie wirklich löschen',
        csvExported: 'Benutzer nach CSV exportiert',
        orderUpdated: 'Reihenfolge aktualisiert',
        itemDeleted: 'Element gelöscht',
        billingPage: 'Abrechnung',
        newInvoice: 'Neue Rechnung',
        totalBilled: 'Gesamtrechnung',
        paid: 'Bezahlt',
        pending: 'Ausstehend',
        overdue: 'Überfällig',
        invoices: 'Rechnungen',
        allStatuses: 'Alle Status',
        paidStatus: 'Bezahlt',
        pendingStatus: 'Ausstehend',
        overdueStatus: 'Überfällig',
        client: 'Kunde',
        amount: 'Betrag',
        date: 'Datum',
        dueDate: 'Fälligkeitsdatum',
        id: 'ID',
        export: 'Exportieren',
        featureInDevelopment: 'Funktion in Entwicklung',
        productsPage: 'Produkte',
        addProduct: 'Produkt hinzufügen',
        editProduct: 'Produkt bearbeiten',
        searchProducts: 'Produkte suchen...',
        category: 'Kategorie',
        price: 'Preis',
        stock: 'Lagerbestand',
        noProducts: 'Keine Produkte',
        noProductsDesc: 'Fügen Sie das erste Produkt hinzu',
        productAdded: 'Produkt hinzugefügt',
        productUpdated: 'Produkt aktualisiert',
        productDeleted: 'Produkt gelöscht',
        confirmDeleteProduct: 'Dieses Produkt löschen?',
        activeStatus: 'Aktiv',
        outOfStock: 'Ausverkauft',
        events: 'Ereignisse',
        addEvent: 'Ereignis hinzufügen',
        eventTitle: 'Ereignistitel',
        eventDate: 'Datum',
        eventDescription: 'Beschreibung',
        eventAdded: 'Ereignis hinzugefügt',
        eventDeleted: 'Ereignis gelöscht',
        more: 'mehr',
        advancedReports: 'Erweiterte Berichte',
        exportPDF: 'PDF exportieren',
        last7Days: 'Letzte 7 Tage',
        last30Days: 'Letzte 30 Tage',
        last3Months: 'Letzte 3 Monate',
        lastYear: 'Letztes Jahr',
        totalRevenuePeriod: 'Gesamtumsatz',
        newUsers: 'Neue Benutzer',
        orders: 'Bestellungen',
        avgRevenue: 'Durchschnittlicher Umsatz',
        revenuePerPeriod: 'Umsatz pro Zeitraum',
        activeUsersPeriod: 'Aktive Benutzer',
        vsPreviousPeriod: 'vs vorheriger Zeitraum',
        direct: 'Direkt',
        organic: 'Organisch',
        referred: 'Empfohlen',
        social: 'Sozial',
        emailTraffic: 'E-Mail',
        recentActivity: 'Letzte Aktivität',
        clearActivity: 'Löschen',
        allActivities: 'Alle',
        creation: 'Erstellung',
        update: 'Aktualisierung',
        deletion: 'Löschung',
        login: 'Anmeldung',
        exportAction: 'Export',
        noActivity: 'Keine Aktivität aufgezeichnet',
        startedSession: 'hat Sitzung gestartet',
        createdUser: 'hat Benutzer erstellt',
        updated: 'hat aktualisiert',
        exported: 'hat exportiert',
        deleted: 'hat gelöscht',
        system: 'System',
        personalInfo: 'Persönliche Informationen',
        changePassword: 'Passwort ändern',
        currentPassword: 'Aktuelles Passwort',
        newPassword: 'Neues Passwort',
        confirmPassword: 'Passwort bestätigen',
        updatePassword: 'Passwort aktualisieren',
        saveChanges: 'Änderungen speichern',
        clickCamera: 'Klicken Sie auf das Kamerasymbol, um Ihren Avatar zu ändern',
        profileUpdated: 'Profil erfolgreich aktualisiert',
        passwordUpdated: 'Passwort erfolgreich aktualisiert',
        passwordsDontMatch: 'Passwörter stimmen nicht überein',
        passwordMinLength: 'Passwort muss mindestens 6 Zeichen haben',
        signIn: 'Anmelden',
        signOut: 'Abmelden',
        password: 'Passwort',
        demoNote: 'Demo: verwenden Sie eine beliebige E-Mail und Passwort (6+ Zeichen)',
        emailRequired: 'E-Mail ist erforderlich',
        passwordRequired: 'Passwort ist erforderlich',
        passwordMin6: 'Passwort muss mindestens 6 Zeichen haben',
        loginError: 'Anmeldefehler',
        notifications: 'Benachrichtigungen',
        markAllRead: 'Alle als gelesen markieren',
        noNotifications: 'Keine Benachrichtigungen',
        siteName: 'Site-Name',
        contactEmail: 'Kontakt-E-Mail',
        language: 'Sprache',
        theme: 'Thema',
        dark: 'Dunkel',
        light: 'Hell',
        primaryColor: 'Primärfarbe',
        roleSystem: 'Rollensystem',
        roleDescription: 'Ändern Sie Ihre Rolle, um zu sehen, wie sich die Berechtigungen anpassen',
        adminRole: 'Admin',
        editorRole: 'Editor',
        viewerRole: 'Betrachter',
        fullAccess: 'Voller Zugriff',
        limitedAccess: 'Eingeschränkte Verwaltung',
        readOnly: 'Nur lesen',
        home: 'Startseite',
        task: 'Aufgabe',
        taskDescription: 'Aufgabenbeschreibung',
        loading: 'Laden...',
    },
}

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
    language: 'es',
    setLanguage: () => { },
    t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('es')
    const [mounted, setMounted] = useState(false)

    useEffect(() => {
        setMounted(true)
        const stored = localStorage.getItem('language')
        if (stored && ['es', 'en', 'fr', 'pt', 'de'].includes(stored)) {
            setLanguage(stored as Language)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', lang)
        }
    }

    const t = (key: string): string => {
        return translations[language]?.[key] || key
    }

    if (!mounted) {
        return (
            <LanguageContext.Provider value={{ language: 'es', setLanguage: handleSetLanguage, t }}>
                {children}
            </LanguageContext.Provider>
        )
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)