'use client'

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'es' | 'en' | 'fr' | 'pt' | 'de'

const translations: Record<Language, Record<string, string>> = {
    es: {
        dashboard: 'Dashboard',
        users: 'Usuarios',
        billing: 'Facturación',
        products: 'Productos',
        analytics: 'Analíticas',
        settings: 'Configuración',
        welcome: 'Bienvenido de vuelta',
        welcomeDesc: 'Aquí tienes un resumen de tu negocio',
        totalRevenue: 'Ingresos Totales',
        activeUsers: 'Usuarios Activos',
        conversionRate: 'Tasa de Conversión',
        responseTime: 'Tiempo de Respuesta',
        monthlyRevenue: 'Ingresos Mensuales',
        activeUsersChart: 'Usuarios Activos',
        userManagement: 'Gestión de Usuarios',
        addUser: 'Agregar Usuario',
        exportCSV: 'Exportar CSV',
        search: 'Buscar',
        name: 'Nombre',
        email: 'Email',
        role: 'Rol',
        status: 'Estado',
        actions: 'Acciones',
        edit: 'Editar',
        delete: 'Eliminar',
        save: 'Guardar',
        cancel: 'Cancelar',
        active: 'Activo',
        inactive: 'Inactivo',
        admin: 'Admin',
        editor: 'Editor',
        user: 'Usuario',
        noUsers: 'No hay usuarios',
        noUsersDesc: 'Agrega el primer usuario para comenzar',
        login: 'Iniciar Sesión',
        logout: 'Cerrar Sesión',
        myProfile: 'Mi Perfil',
        notifications: 'Notificaciones',
        markAllRead: 'Marcar todas como leídas',
        noNotifications: 'No hay notificaciones',
        siteName: 'Nombre del sitio',
        contactEmail: 'Email de contacto',
        saveChanges: 'Guardar cambios',
        password: 'Contraseña',
        currentPassword: 'Contraseña Actual',
        newPassword: 'Nueva Contraseña',
        confirmPassword: 'Confirmar Contraseña',
        updatePassword: 'Actualizar Contraseña',
        personalInfo: 'Información Personal',
        changePassword: 'Cambiar Contraseña',
        language: 'Idioma',
        theme: 'Tema',
        dark: 'Oscuro',
        light: 'Claro',
        primaryColor: 'Color Primario',
        events: 'Eventos',
        calendar: 'Calendario',
        addEvent: 'Agregar Evento',
        eventTitle: 'Título del evento',
        eventDate: 'Fecha',
        eventDescription: 'Descripción',
    },
    en: {
        dashboard: 'Dashboard',
        users: 'Users',
        billing: 'Billing',
        products: 'Products',
        analytics: 'Analytics',
        settings: 'Settings',
        welcome: 'Welcome back',
        welcomeDesc: 'Here\'s a summary of your business',
        totalRevenue: 'Total Revenue',
        activeUsers: 'Active Users',
        conversionRate: 'Conversion Rate',
        responseTime: 'Response Time',
        monthlyRevenue: 'Monthly Revenue',
        activeUsersChart: 'Active Users',
        userManagement: 'User Management',
        addUser: 'Add User',
        exportCSV: 'Export CSV',
        search: 'Search',
        name: 'Name',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        active: 'Active',
        inactive: 'Inactive',
        admin: 'Admin',
        editor: 'Editor',
        user: 'User',
        noUsers: 'No users',
        noUsersDesc: 'Add the first user to get started',
        login: 'Sign In',
        logout: 'Sign Out',
        myProfile: 'My Profile',
        notifications: 'Notifications',
        markAllRead: 'Mark all as read',
        noNotifications: 'No notifications',
        siteName: 'Site Name',
        contactEmail: 'Contact Email',
        saveChanges: 'Save Changes',
        password: 'Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        updatePassword: 'Update Password',
        personalInfo: 'Personal Information',
        changePassword: 'Change Password',
        language: 'Language',
        theme: 'Theme',
        dark: 'Dark',
        light: 'Light',
        primaryColor: 'Primary Color',
        events: 'Events',
        calendar: 'Calendar',
        addEvent: 'Add Event',
        eventTitle: 'Event Title',
        eventDate: 'Date',
        eventDescription: 'Description',
    },
    fr: {
        dashboard: 'Tableau de bord',
        users: 'Utilisateurs',
        billing: 'Facturation',
        products: 'Produits',
        analytics: 'Analytique',
        settings: 'Paramètres',
        welcome: 'Bon retour',
        welcomeDesc: 'Voici un résumé de votre entreprise',
        totalRevenue: 'Revenu Total',
        activeUsers: 'Utilisateurs Actifs',
        conversionRate: 'Taux de Conversion',
        responseTime: 'Temps de Réponse',
        monthlyRevenue: 'Revenu Mensuel',
        activeUsersChart: 'Utilisateurs Actifs',
        userManagement: 'Gestion des Utilisateurs',
        addUser: 'Ajouter Utilisateur',
        exportCSV: 'Exporter CSV',
        search: 'Rechercher',
        name: 'Nom',
        email: 'Email',
        role: 'Rôle',
        status: 'Statut',
        actions: 'Actions',
        edit: 'Modifier',
        delete: 'Supprimer',
        save: 'Enregistrer',
        cancel: 'Annuler',
        active: 'Actif',
        inactive: 'Inactif',
        admin: 'Admin',
        editor: 'Éditeur',
        user: 'Utilisateur',
        noUsers: 'Aucun utilisateur',
        noUsersDesc: 'Ajoutez le premier utilisateur pour commencer',
        login: 'Connexion',
        logout: 'Déconnexion',
        myProfile: 'Mon Profil',
        notifications: 'Notifications',
        markAllRead: 'Tout marquer comme lu',
        noNotifications: 'Aucune notification',
        siteName: 'Nom du site',
        contactEmail: 'Email de contact',
        saveChanges: 'Enregistrer',
        password: 'Mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        updatePassword: 'Mettre à jour le mot de passe',
        personalInfo: 'Informations personnelles',
        changePassword: 'Changer le mot de passe',
        language: 'Langue',
        theme: 'Thème',
        dark: 'Sombre',
        light: 'Clair',
        primaryColor: 'Couleur primaire',
        events: 'Événements',
        calendar: 'Calendrier',
        addEvent: 'Ajouter un événement',
        eventTitle: 'Titre de l\'événement',
        eventDate: 'Date',
        eventDescription: 'Description',
    },
    pt: {
        dashboard: 'Painel',
        users: 'Usuários',
        billing: 'Faturamento',
        products: 'Produtos',
        analytics: 'Análises',
        settings: 'Configurações',
        welcome: 'Bem-vindo de volta',
        welcomeDesc: 'Aqui está um resumo do seu negócio',
        totalRevenue: 'Receita Total',
        activeUsers: 'Usuários Ativos',
        conversionRate: 'Taxa de Conversão',
        responseTime: 'Tempo de Resposta',
        monthlyRevenue: 'Receita Mensal',
        activeUsersChart: 'Usuários Ativos',
        userManagement: 'Gestão de Usuários',
        addUser: 'Adicionar Usuário',
        exportCSV: 'Exportar CSV',
        search: 'Pesquisar',
        name: 'Nome',
        email: 'Email',
        role: 'Função',
        status: 'Status',
        actions: 'Ações',
        edit: 'Editar',
        delete: 'Excluir',
        save: 'Salvar',
        cancel: 'Cancelar',
        active: 'Ativo',
        inactive: 'Inativo',
        admin: 'Admin',
        editor: 'Editor',
        user: 'Usuário',
        noUsers: 'Nenhum usuário',
        noUsersDesc: 'Adicione o primeiro usuário para começar',
        login: 'Entrar',
        logout: 'Sair',
        myProfile: 'Meu Perfil',
        notifications: 'Notificações',
        markAllRead: 'Marcar todas como lidas',
        noNotifications: 'Nenhuma notificação',
        siteName: 'Nome do site',
        contactEmail: 'Email de contato',
        saveChanges: 'Salvar alterações',
        password: 'Senha',
        currentPassword: 'Senha atual',
        newPassword: 'Nova senha',
        confirmPassword: 'Confirmar senha',
        updatePassword: 'Atualizar senha',
        personalInfo: 'Informações pessoais',
        changePassword: 'Alterar senha',
        language: 'Idioma',
        theme: 'Tema',
        dark: 'Escuro',
        light: 'Claro',
        primaryColor: 'Cor primária',
        events: 'Eventos',
        calendar: 'Calendário',
        addEvent: 'Adicionar evento',
        eventTitle: 'Título do evento',
        eventDate: 'Data',
        eventDescription: 'Descrição',
    },
    de: {
        dashboard: 'Dashboard',
        users: 'Benutzer',
        billing: 'Abrechnung',
        products: 'Produkte',
        analytics: 'Analytik',
        settings: 'Einstellungen',
        welcome: 'Willkommen zurück',
        welcomeDesc: 'Hier ist eine Zusammenfassung Ihres Unternehmens',
        totalRevenue: 'Gesamtumsatz',
        activeUsers: 'Aktive Benutzer',
        conversionRate: 'Konversionsrate',
        responseTime: 'Antwortzeit',
        monthlyRevenue: 'Monatlicher Umsatz',
        activeUsersChart: 'Aktive Benutzer',
        userManagement: 'Benutzerverwaltung',
        addUser: 'Benutzer hinzufügen',
        exportCSV: 'CSV exportieren',
        search: 'Suchen',
        name: 'Name',
        email: 'E-Mail',
        role: 'Rolle',
        status: 'Status',
        actions: 'Aktionen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        save: 'Speichern',
        cancel: 'Abbrechen',
        active: 'Aktiv',
        inactive: 'Inaktiv',
        admin: 'Admin',
        editor: 'Editor',
        user: 'Benutzer',
        noUsers: 'Keine Benutzer',
        noUsersDesc: 'Fügen Sie den ersten Benutzer hinzu',
        login: 'Anmelden',
        logout: 'Abmelden',
        myProfile: 'Mein Profil',
        notifications: 'Benachrichtigungen',
        markAllRead: 'Alle als gelesen markieren',
        noNotifications: 'Keine Benachrichtigungen',
        siteName: 'Site-Name',
        contactEmail: 'Kontakt-E-Mail',
        saveChanges: 'Änderungen speichern',
        password: 'Passwort',
        currentPassword: 'Aktuelles Passwort',
        newPassword: 'Neues Passwort',
        confirmPassword: 'Passwort bestätigen',
        updatePassword: 'Passwort aktualisieren',
        personalInfo: 'Persönliche Informationen',
        changePassword: 'Passwort ändern',
        language: 'Sprache',
        theme: 'Thema',
        dark: 'Dunkel',
        light: 'Hell',
        primaryColor: 'Primärfarbe',
        events: 'Ereignisse',
        calendar: 'Kalender',
        addEvent: 'Ereignis hinzufügen',
        eventTitle: 'Ereignistitel',
        eventDate: 'Datum',
        eventDescription: 'Beschreibung',
    },
}

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
    language: 'es',
    setLanguage: () => { },
    t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('es')
    const [mounted, setMounted] = useState(false)

    useEffect(() => {
        setMounted(true)
        const stored = localStorage.getItem('language')
        if (stored && ['es', 'en', 'fr', 'pt', 'de'].includes(stored)) {
            setLanguage(stored as Language)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', lang)
        }
    }

    const t = (key: string): string => {
        return translations[language]?.[key] || key
    }

    if (!mounted) {
        return (
            <LanguageContext.Provider value={{ language: 'es', setLanguage: handleSetLanguage, t }}>
                {children}
            </LanguageContext.Provider>
        )
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => useContext(LanguageContext)